# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-27 15:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personalinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Имя')),
                ('surname', models.CharField(max_length=32, verbose_name='Фамилия')),
                ('patronymic', models.CharField(max_length=32, verbose_name='Отчество')),
                ('birth', models.DateField(verbose_name='День рождения')),
                ('bpl', models.CharField(max_length=100, verbose_name='Место рождения')),
            ],
        ),
    ]
