# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-27 15:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abiturient', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinfo',
            name='nationality',
            field=models.CharField(default='Таджик', max_length=20, verbose_name='Национальность'),
        ),
    ]
