# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-27 15:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abiturient', '0002_personalinfo_nationality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinfo',
            name='nationality',
            field=models.CharField(blank=True, max_length=20, verbose_name='Национальность'),
        ),
    ]
