# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-27 15:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abiturient', '0003_auto_20160527_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinfo',
            name='nationality',
            field=models.CharField(default='', max_length=20, verbose_name='Национальность'),
        ),
    ]
