# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-27 17:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abiturient', '0006_auto_20160527_1725'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personalinfo',
            options={'verbose_name': 'Персональные данные', 'verbose_name_plural': 'Персональные данные'},
        ),
    ]
