# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-30 13:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abiturient', '0009_auto_20160530_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinfo',
            name='avg_mark',
            field=models.FloatField(blank=True, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='birth',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='date_finished',
            field=models.DateField(blank=True, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='doc_number',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='doc_series',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='f_phone',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='homephone',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Домашний телефон'),
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='issuance_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата выдачи паспорта'),
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='m_phone',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='math_mark',
            field=models.PositiveSmallIntegerField(blank=True, max_length=1, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='mobilephone',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Мобильный телефон'),
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='number',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Номер паспорта'),
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='prof_subj_mark',
            field=models.PositiveSmallIntegerField(blank=True, max_length=1, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='russian_mark',
            field=models.PositiveSmallIntegerField(blank=True, max_length=1, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='series',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Серия паспорта'),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='address',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Адрес проживания'),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='bpl',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Место рождения'),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='citizenship',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='Гражданство'),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='education_doc',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='education_lvl',
            field=models.CharField(blank=True, max_length=35, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='f_job',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='f_name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='f_patronymic',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='f_post',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='f_surname',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='finished_school',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='free_or_pay',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='issued',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='Кем выдан паспорт'),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='language',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='m_job',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='m_name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Имя матери'),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='m_patronymic',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Отчество матери'),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='m_post',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='m_surname',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Фамилия матери'),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='math',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='nationality',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Национальность'),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='prof_subj',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='registration',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Прописка'),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='russian',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='speciality',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name=''),
        ),
    ]
