# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-30 14:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abiturient', '0010_auto_20160530_1655'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalinfo',
            name='math',
        ),
        migrations.RemoveField(
            model_name='personalinfo',
            name='prof_subj',
        ),
        migrations.RemoveField(
            model_name='personalinfo',
            name='russian',
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='avg_mark',
            field=models.FloatField(blank=True, null=True, verbose_name='Средний балл'),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='date_finished',
            field=models.DateField(blank=True, null=True, verbose_name='Дата окончания'),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='doc_number',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Номер документа об образовании'),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='doc_series',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Серия документа об образовании'),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='education_doc',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Документ об образовании'),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='education_lvl',
            field=models.CharField(blank=True, max_length=35, null=True, verbose_name='Уровень образования'),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='f_job',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Работа отца'),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='f_name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Имя отца'),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='f_patronymic',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Отчество отца'),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='f_phone',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Телефон отца'),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='f_post',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Должность отца'),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='f_surname',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Фамилия тца'),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='finished_school',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Законченная школа'),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='free_or_pay',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Тип обучения'),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='language',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Изучаемый иностранный язык'),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='m_job',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Работа матери'),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='m_phone',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Телефон матери'),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='m_post',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Должность матери'),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='math_mark',
            field=models.PositiveSmallIntegerField(blank=True, max_length=1, null=True, verbose_name='Оценка по математике'),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='prof_subj_mark',
            field=models.PositiveSmallIntegerField(blank=True, max_length=1, null=True, verbose_name='Оценка по профильному языку'),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='russian_mark',
            field=models.PositiveSmallIntegerField(blank=True, max_length=1, null=True, verbose_name='Оценка по русскому языку'),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='speciality',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Выбранная специальность'),
        ),
    ]
