# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-30 14:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abiturient', '0011_auto_20160530_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinfo',
            name='f_surname',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Фамилия отца'),
        ),
    ]
