# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-30 14:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abiturient', '0012_auto_20160530_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinfo',
            name='f_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон отца'),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='homephone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Домашний телефон'),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='m_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон матери'),
        ),
    ]
