# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-06 17:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abiturient', '0013_auto_20160530_1722'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Personalinfo',
            new_name='Information',
        ),
        migrations.AlterModelOptions(
            name='information',
            options={},
        ),
    ]
