# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-08 16:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abiturient', '0015_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personalinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(blank=True, max_length=30, null=True, verbose_name='Фамилия')),
                ('name', models.CharField(blank=True, max_length=30, null=True, verbose_name='Имя')),
                ('patronymic', models.CharField(blank=True, max_length=30, null=True, verbose_name='Отчество')),
                ('birth', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('bpl', models.CharField(blank=True, max_length=50, null=True, verbose_name='Место рождения')),
                ('citizenship', models.CharField(blank=True, max_length=70, null=True, verbose_name='Гражданство')),
                ('nationality', models.CharField(blank=True, max_length=30, null=True, verbose_name='Национальность')),
                ('homephone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Домашний телефон')),
                ('mobilephone', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Мобильный телефон')),
                ('registration', models.CharField(blank=True, max_length=30, null=True, verbose_name='Прописка')),
                ('address', models.CharField(blank=True, max_length=30, null=True, verbose_name='Адрес проживания')),
                ('series', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Серия паспорта')),
                ('number', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Номер паспорта')),
                ('issued', models.CharField(blank=True, max_length=70, null=True, verbose_name='Кем выдан паспорт')),
                ('issuance_date', models.DateField(blank=True, null=True, verbose_name='Дата выдачи паспорта')),
                ('m_surname', models.CharField(blank=True, max_length=30, null=True, verbose_name='Фамилия матери')),
                ('m_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='Имя матери')),
                ('m_patronymic', models.CharField(blank=True, max_length=30, null=True, verbose_name='Отчество матери')),
                ('m_job', models.CharField(blank=True, max_length=30, null=True, verbose_name='Работа матери')),
                ('m_post', models.CharField(blank=True, max_length=30, null=True, verbose_name='Должность матери')),
                ('m_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон матери')),
                ('f_surname', models.CharField(blank=True, max_length=30, null=True, verbose_name='Фамилия отца')),
                ('f_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='Имя отца')),
                ('f_patronymic', models.CharField(blank=True, max_length=30, null=True, verbose_name='Отчество отца')),
                ('f_job', models.CharField(blank=True, max_length=30, null=True, verbose_name='Работа отца')),
                ('f_post', models.CharField(blank=True, max_length=30, null=True, verbose_name='Должность отца')),
                ('f_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон отца')),
                ('education_lvl', models.CharField(blank=True, max_length=35, null=True, verbose_name='Уровень образования')),
                ('speciality', models.CharField(blank=True, max_length=40, null=True, verbose_name='Выбранная специальность')),
                ('free_or_pay', models.CharField(blank=True, max_length=30, null=True, verbose_name='Тип обучения')),
                ('finished_school', models.CharField(blank=True, max_length=30, null=True, verbose_name='Законченная школа')),
                ('date_finished', models.DateField(blank=True, null=True, verbose_name='Дата окончания')),
                ('education_doc', models.CharField(blank=True, max_length=30, null=True, verbose_name='Документ об образовании')),
                ('doc_series', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Серия документа об образовании')),
                ('doc_number', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Номер документа об образовании')),
                ('math_mark', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Оценка по математике')),
                ('russian_mark', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Оценка по русскому языку')),
                ('prof_subj_mark', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Оценка по профильному предмету')),
                ('avg_mark', models.FloatField(blank=True, null=True, verbose_name='Средний балл')),
                ('language', models.CharField(blank=True, max_length=30, null=True, verbose_name='Изучаемый иностранный язык')),
            ],
            options={
                'verbose_name': 'данные об абитуриенте',
                'verbose_name_plural': 'Данные об абитуриенте',
            },
        ),
        migrations.DeleteModel(
            name='Info',
        ),
        migrations.DeleteModel(
            name='Information',
        ),
    ]
