# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-14 10:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abiturient', '0016_auto_20160608_1658'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalinfo',
            name='education_doc',
        ),
        migrations.RemoveField(
            model_name='personalinfo',
            name='education_lvl',
        ),
        migrations.RemoveField(
            model_name='personalinfo',
            name='free_or_pay',
        ),
    ]
